const constituency = [
  {
    state: "Abia",
    senatorial_districts: ["Abia Central", "Abia North", "Abia South"],
    lga: [
      "Abia North",
      "Abia South",
      "Arochukwu",
      "Ohafia",
      "Bende",
      "Isialangwa North",
      "Isialangwa South",
      "Isuikwuato",
      "Umunneochi",
      "Ohingwa",
      "Ugwunagho",
      "Osisioma",
      "Umuahia North",
      "Umuahia South",
      "Ikwunano",
      "Ukwa West",
      "Ukwa East",
    ],
  },
  {
    state: "Adamawa",
    senatorial_districts: ["Adamawa Central", "Adamawa North", "Adamawa South"],
    lga: [
      "Demsa",
      "Numan",
      "Lamurde",
      "Fufore",
      "Song",
      "Gombi",
      "Hong",
      "Guyuk",
      "Shelleng",
      "Madagali",
      "Michika",
      "Mayo",
      "Belwa",
      "Ganye",
      "Toungo",
      "Toungo",
      "Yola North",
      "Yola South",
      "Gire",
      "Maiha",
      "Muibi North",
      "Muibi South",
    ],
  },
  {
    state: "Akwa-ibom",
    senatorial_districts: ["Akwa Ibom North East", "Akwa Ibom North West", "Akwa Ibom South"],
    lga: [
      "Etim Ekpo",
      "ika",
      "Abak",
      "Onna",
      "Esit Eket",
      "ibeno",
      "Etinan",
      "Nsit Ibom",
      "Nsit Ubium",
      "Ikono",
      "ini",
      "Ikot Abasi",
      "Mkpat Enin",
      "Eastern Obolo",
      "Ikot Ekpene",
      "Essien Udirn",
      "Obot Akara",
      "Itu",
      "ihiono Ihom",
      "Oron",
      "Mho",
      "Okoho",
      "Udung Uko",
      "Urue Offong",
      "Oruko",
      "Oruk Anam",
      "Ukanafun",
      "Uyo",
      "Uruan",
      "Nsit Atai",
      "ihesikpo Asutan",
    ],
  },
  {
    state: "Anambra",
    senatorial_districts: ["Anambra Central", "Anambra North", "Anambra South"],
    lga: [
      "Anambra East",
      "Anambra West",
      "Onitsha North",
      "Onitsha South",
      "Ogbaru",
      "Ayamelum",
      "Oyi",
      "Aguata",
      "Awka North",
      "Awka South",
      "Anaocha",
      "Njikoka",
      "Dunukofia",
      "Idemili North",
      "Idemili South",
      "Ihiala",
    ],
  },
  {
    state: "Bauchi",
    senatorial_districts: ["Bauchi Central", "Bauchi North", "Bauchi South"],
    lga: [
      "Alkaleri",
      "Kirfi",
      "Katagum",
      "Bauchi",
      "Bogoro",
      "Dass",
      "Tafawa Balewa",
      "Darazo",
      "Ganjuwa",
      "Gamawa",
      "Shira",
      "Giade",
      "Jama'are",
      "Itas",
      "Gadau",
      "Misau",
      "Dambam",
      "Ningi",
      "Warji",
      "Toro",
      "Zaki",
    ],
  },
  {
    state: "Bayelsa",
    senatorial_districts: ["Bayelsa Central", "Bayelsa East", "Bayelsa West"],
    lga: ["Brass", "Nembe", "Sagbama", "Ekerermor", "Ogbia", "Southern Ijaw", "Yenagoa", "K-Opokuma"],
  },
  {
    state: "Benue",
    senatorial_districts: ["Benue North East", "Benue North West", "Benue South"],
    lga: [
      "Ado",
      "Ogbadibo",
      "Okpokwu",
      "Apa",
      "Agatu",
      "Buruku",
      "Gboko",
      "Tarka",
      "Makurdi",
      "Guma",
      "Gwer East",
      "Gwer West",
      "Katsina Ala",
      "Logo",
      "Ukum",
      "Konshisha",
      "Vandekiya",
      "Kwande",
      "Ushongo",
      "Ohimini",
      "Otukpo",
    ],
  },
  {
    state: "Borno",
    senatorial_districts: ["Borno Central", "Borno North", "Borno South"],
    lga: [
      "Askira-Uba",
      "Hawul",
      "Kalabalge",
      "Bama",
      "Ngala",
      "Biu",
      "Bayo",
      "Shani",
      "Kwaya Kusar",
      "Chibok",
      "Gwoza",
      "Damboa",
      "Dikwa",
      "Mafa",
      "Konduga",
      "Jere",
      "Gubio",
      "Kaga",
      "Magumeri",
      "Kukawa",
      "Mobbar",
      "Abdam",
      "Guzarnala",
      "Maiduguri Metropolitan",
      "Monguno",
      "Matre",
      "Nganzai",
    ],
  },
  {
    state: "Cross River",
    senatorial_districts: ["Cross River Central", "Cross River North", "Cross River South"],
    lga: [
      "Akamkpa",
      "Biase",
      "Abi",
      "Yakurr",
      "Boki",
      "ikom",
      "Calabar Municipal",
      "Odukpani",
      "Akpabuyo",
      "Bakassi",
      "Obanliku",
      "Obudu",
      "Bakwarra",
      "Obubra",
      "Etung",
      "Ogoja",
      "Yala",
    ],
  },
  {
    state: "Delta",
    senatorial_districts: ["Delta Central", "Delta North", "Delta South"],
    lga: [
      "Aniocha",
      "Oshimili",
      "Bomadi",
      "Patani",
      "Burutu",
      "Ethiope East",
      "Ethiope West",
      "Ika North East",
      "lka South",
      "Isoko North",
      "Isoko South",
      "Ndokwa East",
      "Ndokwa West",
      "Ukwuani",
      "Okpe",
      "Sapele",
      "Uvwie",
      "Ughelli North",
      "Ughelli South",
      "Udu",
      "Warri South",
      "Warri West",
      "Warri North",
    ],
  },
  {
    state: "Ebonyi",
    senatorial_districts: ["Ebonyi South", "Ebonyi Central", "Ebonyi North"],
    lga: [
      "Abakaliki",
      "lzzi",
      "Ishielu",
      "Ezza- North",
      "Ikwo",
      "Ezza South",
      "Ivo",
      "Ohaozara",
      "Onicha",
      "Ohaukwu",
      "Ebonyi",
      "Afikpo North",
      "Afikpo South",
    ],
  },
  {
    state: "Edo",
    senatorial_districts: ["Edo South", "Edo Central", "Edo North"],
    lga: [
      "Egor Ikpoba Okha",
      "Esan Central",
      "Igueben",
      "Esan West",
      "Esan North East",
      "Esan South East",
      "Oredo",
      "Etsako East",
      "Etsako West",
      "Etsako Central",
      "Orhionmwon Uhunmwode",
      "Ovia South-West",
      "Ovia North East",
      "Owan East",
      "Owan West",
    ],
  },
  {
    state: "Ekiti",
    senatorial_districts: ["Ekiti South", "Ekiti Central", "Ekiti North"],
    lga: [
      "Ado Ekiti",
      "lrepodun",
      "Ifelodun",
      "Ekiti South West",
      "lkere",
      "Orun",
      "Ise",
      "Emure",
      "Gbonyin",
      "Ekiti East",
      "Moba",
      "Lejemeje",
      "ldo Osi",
      "Ijero",
      "Ekiti West",
      "Efon",
      "Ikole",
      "Oye North",
    ],
  },
  {
    state: "Enugu",
    senatorial_districts: ["Enugu North", "Enugu East", "Enugu West"],
    lga: [
      "Enugu East",
      "Esi Uzo",
      "Enugu North",
      "Enugu South",
      "Ezeagu Udi",
      "Igboeze North",
      "Igboeze North",
      "Nkanu East",
      "Nkanu West",
      "Nsukka",
      "Igboeze South",
      "Igbo Etiti",
      "Uzo Uwani",
      "Aminri Agwu",
      "Oji Uzo",
    ],
  },
  {
    state: "Gombe",
    senatorial_districts: ["Gombe Central", "Gombe North", "Gombe South"],
    lga: ["Akko", "Balanga Billiri", "Dukku Natada", "Kwami Funakaye Gombe", "Kakungo Shongom", "Yamaltu Deba"],
  },
  {
    state: "Imo",
    senatorial_districts: ["Imo East", "Imo North", "Imo West"],
    lga: [
      "Aboh Mbaise",
      "Ngor Okpala",
      "Ahiazu Mbaise",
      "Ezinnihitte",
      "Ideatto North",
      "Ideatto South",
      "Mbaitoli Ikeduru",
      "Onumino Okigwe Isiala Mbano",
      "Orlu Orsu Oru East",
      "Owerri Municipal North West",
      "Ohaji Egbema Oguta",
      "Oru West",
      "Ehime Mbano Ihitte Uhoma Obowo",
    ],
  },
  {
    state: "Jigawa",
    senatorial_districts: ["Jigawa North - West", "Jigawa North – East", "Jigawa South – West"],
    lga: [
      "Babura Garki",
      "Birnin Kadu Buji",
      "Birniwa Guri",
      "Kiri Kasamma",
      "Gwaram",
      "Gumel",
      "Maigatari",
      "Tankar",
      "Gagarawa",
      "Hadejia",
      "Auyo",
      "Hausa",
      "Jahun",
      "Miga",
      "Madori",
      "Kaugama",
      "Yankashi",
      "Gwiwa",
      "Roni",
      "Kazaure",
      "Ringim",
      "Taura",
      "Dutse",
      "Kiyawa",
    ],
  },
  {
    state: "Kaduna",
    senatorial_districts: ["Kaduna Central", "Kaduna North", "Kaduna South"],
    lga: [
      "Kaduna North",
      "Zaria",
      "Soba",
      "Igabi",
      "Ikara Kubau",
      "Makarfi Kudan",
      "Lere",
      "Kachia",
      "Kagarko",
      "Kajuru",
      "Chikun",
      "Jemaa",
      "Sanga",
      "Birnin",
      "Giwa",
      "Gwari",
      "Sabon Gari",
      "Kaduna South",
      "Kaura",
      "Kauru",
      "Jaba",
      "Zangon Kafat",
    ],
  },
  {
    state: "Kano",
    senatorial_districts: ["Kano South", "Kano Central", "Kano North"],
    lga: [
      "Tsanyawa Kunchi",
      "Wudil Garko",
      "Minjibir Ungogo",
      "Fagge",
      "Sumaila Takai",
      "Kura Madobi Garun Mallam",
      "Nassarawa",
      "Kumbotso",
      "Karaye Rogo",
      "Tarauni",
      "Municipal",
      "Gwarzo Kabo",
      "Gezawa Gabasawa",
      "Doguwa Tadun Wada",
      "Dawakin Tofa Tofa Rimin Gado",
      "Dawakin Kudu Warawa",
      "Dambatta Makoda",
      "Gwale",
      "Dala",
      "Bichi",
      "Rano Bunkure Kibiya",
      "Bebeji",
      "Kiru",
      "Shanono",
      "Bagawai",
      "Albasu",
      "Gaya/",
      "Ajingi",
    ],
  },
  {
    state: "Katsina",
    senatorial_districts: ["Katsina Central", "Katsina North", "Katsina South"],
    lga: [
      "Bakori Danja",
      "Batagarawa",
      "Charanchi Rimi",
      "Batsari",
      "Safana Danmusa",
      "Bindawa",
      "Mani",
      "Daura",
      "Mai'aduna Sandamu",
      "Dutsin-ma",
      "Kurfi",
      "Faskari",
      "Kankara Sabuwa",
      "Dandume",
      "Funtua",
      "Kankia",
      "Kusada",
      "Ingawa",
      "Jibia",
      "Kaita",
      "Kafur",
      "Malumfashi",
      "Katsina",
      "Dutsi",
      "Mashi",
      "Matazu",
      "Musawa",
      "Bature",
      "Zango",
    ],
  },
  {
    state: "Kebbi",
    senatorial_districts: ["Kebbi Central", "Kebbi North", "Kebbi South"],
    lga: [
      "Arewa",
      "Dandi",
      "Arugungu",
      "Augie",
      "Bagodu",
      "Suru",
      "Kebbi Kalgo",
      "Zunza",
      "Fakai",
      "Sakaba",
      "Wasadu",
      "Danko",
      "Zuru",
      "Gwandu",
      "Aliero",
      "Koko-Besse",
      "Maiyama",
      "Yauri",
      "Shanga",
      "Ngaski",
    ],
  },
  {
    state: "Kogi",
    senatorial_districts: ["Kogi Central", "Kogi East", "Kogi West"],
    lga: [
      "Adavi",
      "Okehi",
      "Ajaokuta",
      "Ankpa",
      "Omala",
      "Olamaboro",
      "Bassa",
      "Dekina",
      "Idah",
      "Igalamela",
      "Ibaji",
      "Ofu",
      "Kabba-Bunu",
      "Ijumu",
      "Lokoja",
      "Kogi",
      "Okene",
      "Ogori-Magogo",
      "Yagba East",
      "Yagba West",
      "Mopamuro",
    ],
  },
  {
    state: "Kwara",
    senatorial_districts: ["Kwara Central", "Kwara North", "Kwara South"],
    lga: [
      "Baruten Kaima",
      "Edu",
      "Moro",
      "Patigi",
      "Ekiti",
      "Irepodune",
      "Isin",
      "Oke-Ero",
      "Ifelodun",
      "Offa",
      "Oyun",
      "Ilorin East",
      "Ilorin South",
      "Illorin West",
      "Asa",
    ],
  },
  {
    state: "Lagos",
    senatorial_districts: ["Lagos West", "Lagos Central", "Lagos East"],
    lga: [
      "Surulere I",
      "Surulere II",
      "Somola",
      "Oshodi I",
      "Oshodi II",
      "Ojo",
      "Mushin I",
      "Mushin II",
      "Lagos Mainland",
      "Lagos Island I",
      "Lagos Island II",
      "Kosofe",
      "Ikorodu",
      "Ikeja",
      "Ifako Ijaiye",
      "Ibeju-Lekki",
      "Epe",
      "Eti-Osa",
      "Badagry",
      "Alimosho",
      "Apapa",
      "Amuwo Odofin",
      "Ajeromi Ifelodun",
      "Agege",
    ],
  },
  {
    state: "Niger",
    senatorial_districts: ["Niger East", "Niger North", "Niger South"],
    lga: [
      "Katcha Gbako Bida",
      "Bosso Paiko",
      "Chanchaga",
      "Gurara",
      "Suleja",
      "Tafa",
      "Edati",
      "Lavun",
      "Mokwa",
      "Magama Rijau",
      "Kontagora",
      "Wushishi",
      "Mariga",
      "Mashegu",
      "Shiroro",
      "Rafi",
      "Munya",
      "Agaie",
      "Lapai",
      "Borgu",
      "Agwara",
    ],
  },
  {
    state: "Ogun",
    senatorial_districts: ["Ogun Central", "Ogun East", "Ogun West"],
    lga: [
      "Abeokuta South",
      "Ado-Oda",
      "Ota",
      "Abeokuta North",
      "Obafemi Owode",
      "Odeda",
      "Egbado North",
      "Imeko Afon",
      "Egbado South",
      "Ipokia",
      "Ifo",
      "Ekwekoro",
      "Ijebu North",
      "Ijebu East",
      "Ogun Waterside",
      "Ijebu Ode",
      "Ijebu North East",
      "Odogbolu",
      "Ikenne",
      "Shagamu",
      "Remo North",
    ],
  },
  {
    state: "Ondo",
    senatorial_districts: ["Ondo Central", "Ondo North", "Ondo South"],
    lga: [
      "Akoko North East",
      "Akoko North West",
      "Akure South",
      "Akure North",
      "Adanre",
      "Ifedore",
      "Ileoluji-Okeibo",
      "Odigbo",
      "Okitipupa",
      "Irele",
      "Ilaje",
      "Eseodo",
      "Ondo East",
      "Owo",
      "Ose",
      "Ondo West",
    ],
  },
  {
    state: "Osun",
    senatorial_districts: ["Osun Central", "Osun East", "Osun West"],
    lga: [
      "Irepodun",
      "Olorunda",
      "Oshogbo",
      "Orolu",
      "Boripe",
      "Ifelodun",
      "Odo-Otin",
      "Boluwaduro Ifedayo",
      "Ila",
      "Atakumnosa East",
      "Atakunmosa West",
      "Ilesa West",
      "Ilesa East",
      "Obokun Oraide",
      "Ife Central",
      "Ife East",
      "Ife North",
      "Ife South",
      "Aydire",
      "Iwo",
      "Ola-Oluwa",
      "Ayedaade",
      "Irewole",
      "Isokan",
      "Ede North",
      "Ede South",
      "Egbedore",
      "Ejigbo",
    ],
  },
  {
    state: "Oyo",
    senatorial_districts: ["Oyo Central", "Oyo North", "Oyo South"],
    lga: [
      "Afijio",
      "Atiaba East",
      "Oyo West",
      "Akinyele",
      "Lagelu",
      "Egbeda",
      "Ona-Ara",
      "Ibarapa Central",
      "Ibarapa North",
      "Ibarapa East",
      "Ido",
      "Atisbo",
      "Saki East",
      "Saki West",
      "Irepo",
      "Orelope",
      "OLorunsogo",
      "Iseyin",
      "Itesiwaju",
      "Kajola",
      "Iwajowa",
      "Ogbomoso North",
      "Ogbomosho South",
      "Orire",
      "Ogo-Oluwa",
      "Surulere",
      "Oluyole",
      "Ibadan North-East",
      "Ibadan South-East",
      "Ibadan South West",
      "Ibadan North",
    ],
  },
  {
    state: "Plateau",
    senatorial_districts: ["Plateau Central", "Plateau North", "Plateau South"],
    lga: [
      "Barikinladi",
      "Riyom",
      "Mangu",
      "Bokkos",
      "Bassa",
      "Jos North",
      "Jos South",
      "Jos East",
      "Paskshin",
      "Kanke",
      "Kanam",
      "Langtang North",
      "Langtang South",
      "Shendarn",
      "Mikang",
      "Qua'anPan",
      "Wase",
    ],
  },
  {
    state: "Rivers",
    senatorial_districts: ["Rivers East", "Rivers South East", "Rivers West"],
    lga: [
      "Ahoda East",
      "Abua",
      "Odual",
      "Ahoda West",
      "Ogba",
      "Ebgema",
      "Ndoni",
      "Akuku-Toru",
      "Asari-Toru",
      "Degema",
      "Bonny",
      "Eleme",
      "Oyigbo",
      "Tai",
      "Etehe",
      "Omuma",
      "Obio",
      "Akpor",
      "Okrika",
      "Ogu",
      "Bolo",
      "Port Harcourt I",
      "Port Harcout II",
    ],
  },
  {
    state: "Sokoto",
    senatorial_districts: ["Sokoto East", "Sokoto North", "Sokoto South"],
    lga: [
      "Isa",
      "S.Birni",
      "Goronyo",
      "Gada",
      "Mela",
      "Gwadabawa",
      "Rabah",
      "Wurno",
      "Gudu",
      "Tangaza",
      "Binji",
      "Silame",
      "Kware",
      "Wamakko",
      "Sokoto North",
      "Sokoto South",
      "Shuni",
      "Tureta",
      "Bodinga",
      "Yabo",
      "Shagari",
      "Kebbe",
      "Tambuwal",
    ],
  },
  {
    state: "Taraba",
    senatorial_districts: ["Taraba Central", "Taraba North", "Taraba South"],
    lga: [
      "Bali",
      "Gassol",
      "Donga",
      "Ussa",
      "Takum",
      "Gashaka",
      "Kurmi",
      "Sardauna",
      "Ini",
      "Wukari",
      "K-Lamido",
      "Lau",
      "Ardo-Kola",
      "Jalingo",
      "Zing",
      "Yorro",
    ],
  },
  {
    state: "Yobe",
    senatorial_districts: ["Yobe East", "Yobe North", "Yobe South"],
    lga: [
      "Bade",
      "Jakusko",
      "Bursari",
      "Geidam",
      "Yunusari",
      "Damaturu",
      "Gujba",
      "Gulani",
      "Tarmuwa",
      "Fika",
      "Fune",
      "Yusufari",
      "Karasuwa",
      "Machina",
      "Nguru",
      "Potiskum",
      "Nangore",
    ],
  },
  {
    state: "Zamfara",
    senatorial_districts: ["Zamfara Central", "Zamfara North", "Zamfara West"],
    lga: [
      "Kaura-Namoda",
      "Birnin-Magaji",
      "Shinkafi",
      "Zurmi",
      "Gasau Tsafe",
      "Bungudu",
      "Mar",
      "Talata",
      "Anka",
      "Marafa",
      "Bakura",
      "Maradun",
      "Bukkuyum",
      "Gummi",
    ],
  },
  {
    state: "FCT",
    senatorial_districts: ["Federal Capital Territory"],
    lga: ["Abaji", "Abuja Municipal", "Gwagwalada", "Kuje", "Bwari", "Kwali"],
  },
];
